---
framework: mocha 
blocklist:
  - './plugins/aws/cloudformation/driftDetection.spec.js##driftDetection'
preRun:
  command:
    - npm install
preMerge:
  pattern:
    - "./**/*.spec.js"
postMerge:
  env:
    CODE: ${{secrets.english_code}}
  pattern:
    - "./**/*.spec.js"
postRun:
  command:
    - node --version
parallelism: 4
version: 1.0.0
