---
# THIS IS A SAMPLE ".tas.yml" CONFIGURATION FILE
#
# supported frameworks: mocha|jest|jasmine
framework: mocha
blocklist:
  - './plugins/aws/cloudformation/driftDetection.spec.js##driftDetection##run##should FAIL if CloudFormation stack is in drifted state'

preRun:
  # set of commands to run before running the tests
  # for eg `yarn install`, `yarn build`
  command:
    # change the command according to the package manager used.
    # For eg, npm ci, yarn install
    - npm install

postMerge:
  # glob-pattern for identifying the test files
  pattern:
    # glob-patterns to discover tests to run in case of postMerge
    - ./**/*.spec.js
    # - "./unit_test_folder_B/**/*.ts"
postRun:
     command:
        - node --version
